on:
  push:
     branches:
       - main
       - master

jobs:
  notebook:
    name: render-notebook
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown", "dplyr", "ggplot2", "rprojroot", "sf", "leaflet"))'
      - name: Render notebook
        run: Rscript -e 'rmarkdown::render("notebooks/index.Rmd", output_dir = "../docs")'
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/
 checkout-and-deploy:
   runs-on: ubuntu-22.04
   needs: notebook
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Download artifact
       uses: actions/download-artifact@v2
       with:
         name: docs
         path: docs
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
        build_dir: docs
        branch: gh-pages
  